# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-02-13 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0002_tarefa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('conta_id', models.AutoField(primary_key=True, serialize=False)),
                ('conta_nome', models.CharField(max_length=200)),
                ('conta_data_vencimento', models.DateField()),
                ('pago', models.BooleanField()),
            ],
        ),
    ]
